import gdown

# URL file Google Drive (thay đổi từ dạng "view" sang "uc" để gdown hoạt động)
url = "https://3zfmbk-my.sharepoint.com/personal/xmbll_3zfmbk_onmicrosoft_com/_layouts/15/download.aspx?UniqueId=cdea891f-b8c9-433d-b511-8b8abece6baa&Translate=false&tempauth=v1.eyJzaXRlaWQiOiI2ZmYyZTZkMy1iZmQ0LTRmMDAtYjZkZS0yZDE2NjE1ZTRiYzciLCJhcHBfZGlzcGxheW5hbWUiOiJhbGlzdCIsImFwcGlkIjoiMjIzNTg5MDYtOTI2OS00ZjQzLWIyMzUtMDU3MjU4ZjQ1ZTA0IiwiYXVkIjoiMDAwMDAwMDMtMDAwMC0wZmYxLWNlMDAtMDAwMDAwMDAwMDAwLzN6Zm1iay1teS5zaGFyZXBvaW50LmNvbUAxN2QwODU4Yy04MTliLTQxY2ItODc0My00NDg2ODQyNDViYjIiLCJleHAiOiIxNzM3NDcxMzU5In0.CgoKBHNuaWQSAjY0EgsIgLzN5auL3T0QBRoOMjAuMTkwLjE0NC4xNzAqLFpabXhQTUlINm04Nm9UdnBpS2FLejNtTXBpQjhFNm94a1FaNVd3Z1FmV2c9MJ4BOAFCEKF5tS5DYABAUldrhX8MAlJKEGhhc2hlZHByb29mdG9rZW5SCFsia21zaSJdcikwaC5mfG1lbWJlcnNoaXB8MTAwMzIwMDI0NzNiMTc4NEBsaXZlLmNvbXoBMoIBEgmMhdAXm4HLQRGHQ0SGhCRbspIBBmJvbGFuZ5oBAmRhogEceG1ibGxAM3pmbWJrLm9ubWljcm9zb2Z0LmNvbaoBEDEwMDMyMDAyNDczQjE3ODSyAQ5hbGxmaWxlcy53cml0ZcgBAQ.lEuZE3Rlg3Td8LYXys-H0PGc06XkBVLYTZOcQBwvCTo&ApiVersion=2.0"

# Đường dẫn lưu file sau khi tải
output = "/mnt/a.qcow2"  # Đường dẫn đầy đủ nơi lưu file

# Tải file
gdown.download(url, output, quiet=False)

print(f"File đã được tải về và lưu tại: {output}")
